[project]
name = "carla"
version = "0.1.0"
description = "captures images inside the carla simulator to be used for validation dataset"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
